[project]
name = "rl-sdk"
version = "0.1.0"
description = "RLaaS telemetry client"
requires-python = ">=3.9"
dependencies = [
  "httpx>=0.27.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
pythonpath = ["src"]
