global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8000']
  - job_name: collector
    metrics_path: /metrics
    static_configs:
      - targets: ['collector:8100']
  - job_name: reward
    metrics_path: /metrics
    static_configs:
      - targets: ['reward:8080']
  - job_name: trainer
    metrics_path: /metrics
    static_configs:
      - targets: ['trainer:8090']
